### DISCUSSION TITLE
Agents / Teams Creation from YAML

### DISCUSSION THREAD

**Discussion by alpha-xone** [agno-agi/agno#3020] [Ideas]
Hey all 👋,

I’ve been experimenting with a small helper module, `builder.py`, that lets us define and spin up agents / teams purely from YAML. The basic idea is:

```yaml
# finance_agent.yml
analyst:
  class: agno.agent.Agent
  params:
    model:
      class: agno.models.deepseek.DeepSeek
    tools:
      - class: agno.tools.yfinance.YFinanceTools
        params:
          stock_price: true
          analyst_recommendations: true
          stock_fundamentals: true
          historical_prices: true
          company_info: true
          company_news: true
    add_datetime_to_instructions: true
    show_tool_calls: true
    markdown: true
    instructions:
      - 'You are a seasoned Wall Street analyst with deep expertise in market analysis! 📊'
      - ...
```

And then in Python:

```python
from agno.utils.builder import agno

analyst = agno("finance_agent")
```

### Why this could help

1. **Readable & editable**  
   Storing agent configurations in YAML means you can tweak names, classes, and parameters without diving into code.  
2. **Reusable workflows**  
   The same YAML file can power different scripts, notebooks, or CI jobs—no copy-&-paste.  
3. **Easy sharing**  
   Team members can swap YAML snippets instead of explaining “here’s how you instantiate Agent X in Python.”

---

#### Question for the maintainers  
Where would you expect this to live in our repo? A few possibilities:

- **`agno/utils/yaml.py`** alongside the other utilities  
- **`agno/scripts/yaml.py`** alongside the other scripts
- **`agno/tools/yaml.py`** a new folder with other tools potentially created in the future

Happy to move it wherever makes the most sense, and I can add a quick smoke test + docs once the location is settled. Let me know your thoughts! 🚀

Another example to create the language team:

```yaml
multi_lang:
  class: agno.team.team.Team
  params:
    name: Multi Language Team
    mode: route
    model:
      class: agno.models.openai.OpenAIChat
      params:
        id: gpt-4.5-preview
    members:
      - class: agno.agent.Agent
        params:
          name: English Agent
          role: You can only answer in English
          model:
            class: agno.models.openai.OpenAIChat
            params:
              id: gpt-4.5-preview
          instructions:
            - You must only respond in English
      - class: agno.agent.Agent
        params:
          name: Chinese Agent
          role: You can only answer in Chinese
          model:
            class: agno.models.deepseek.DeepSeek
          instructions:
            - You must only respond in Chinese
    show_tool_calls: true
    markdown: true,
    instructions:
      - "You are a language router that directs questions to the appropriate language agent."
      - ...
    show_members_responses: true
```

**Comment by monali7-d** [comment]
Hi @alpha-xone , thanks for reaching out and supporting Agno. I’ve shared this with the team, we’re working through all requests one by one and will get back to you soon.
If it’s urgent, please let us know. We appreciate your patience!

**Comment by alpha-xone** [comment]
Thanks - kindly take your time.

Another benefit is keeping the codes simple by removing all the imports:

```python
from agno.utils.builder import agno

memory = agno('agents/mem0', db_path='tmp/chat.chroma', collection_name='memories')
agent = agno('agents/chatbot', memory=memory)
```

The yaml files looks something like below - it uses `mem0` in another PR (#3000):

```yaml
# agents/mem0.yml
mem0_memory:
  class: .memory.mem0.Mem0Memory
  params:
    user_id: ${user_id}
    agent_id: ${agent_id}
    session_id: ${session_id}
    config:
      graph_store:
        provider: neo4j
        config:
          url: bolt://localhost:7687
          username: neo4j
          password: '00000000'
      embedder:
        provider: huggingface
        config:
          model: sentence-transformers/all-MiniLM-L6-v2
          embedding_dims: 384
      vector_store:
        provider: chroma
        config:
          path: ${db_path}
          collection_name: ${collection_name}
      llm:
        provider: deepseek
        config:
          model: deepseek-chat
          deepseek_base_url: https://api.deepseek.com
          api_key: ${DEEPSEEK_API_KEY}
```

```yaml
# agents/chatbot.yml
chatbot:
  class: agno.agent.Agent
  params:
    name: Companion Buddy Agent
    user_id: ${user_id}
    model:
      class: agno.models.deepseek.DeepSeek
    memory: ${memory}
    enable_user_memories: true
    add_history_to_messages: true
    description: Companion Buddy - Casual Emotional Support
```
